### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by diraol** [plotly/plotly-toolpanel#12]
Hi friends, I'm trying to use `plotly-toolpanel`, but I wasn't able to make the `simple` example work.

It seems that one of the reasons is a problem with CORS, regarding the cross-origin request to get one plotly chart. But that's ok to overcome, I've built a offline chart in order to achieve the same 'result'.

But now I'm facing problems with the toolpanel itself.

It seems to be a problem with the `toolpanel-standalone-bundle.js` and `toolpanel-dependencies-bundle.js` files. The first one is just empty.

How can I compile this files from the sources? Do you guys use any tools or scripts for that?

I would also like to say that I wish to contribute with the project as soon as I can make it work locally on my computer =)

Cheers!

**Comment by RDCH106** [comment]
The toolpanel is not working!
I do not why the `toolpanel-standalone-bundle.js` is empty...

The problem starts in [`simple.js`](https://github.com/plotly/plotly-toolpanel/blob/master/dist/examples/simple/simple.js#L3) when the Plotly and ToolPanel objects are grabbed from the window scope:

``` javascript
3 /* Grab the Plotly and ToolPanel objects from the window scope */
4 var Plotly = window.Plotly;
5 var ToolPanel = window.ToolPanel;  // The problem starts here --> Undefined Object
```

**Comment by laxmim19** [comment]
@diraol hey, did you find any solution for the above query.

**Comment by diraol** [comment]
Sorry @laxmim19 I was just doing some benchmarks at the time and since this feature was not working I just dropped it from the benchmark.
